### DISCUSSION TITLE
Adguard Home inside a jail - DNS not working

### DISCUSSION THREAD

**Discussion by BenRoe** [Jip-Hop/jailmaker#102] [General]
Hi,
i try to get Adguard Home running inside a jail.

Used the docker template and only changed the systemd_nspawn_user_args
```yaml
systemd_nspawn_user_args=--network-macvlan=eno1
        --resolv-conf=off
        --system-call-filter='add_key keyctl bpf'
        --bind='/mnt/tank/jailmaker/docker-data/adguard:/docker-data/adguard'
```

/etc/resolv.conf inside the jail
```
nameserver 127.0.0.1
search .
```

Added a static IP like described [here](https://github.com/Jip-Hop/jailmaker/blob/main/docs/network.md#setting-a-static-ip).

My compose.yaml
```yaml
version: "3"

services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguardhome
    deploy:
      resources:
        limits:
          cpus: '0.50' # max. 50%
          memory: 300m
        reservations:
          cpus: '0.1'
          memory: 100m
    volumes:
      - '/docker-data/adguard/conf:/opt/adguardhome/conf'
      - '/docker-data/adguard/work:/opt/adguardhome/work'
    ports:
        # DNS
        - 53:53/tcp
        - 53:53/udp
        # DHCP server
        #- 67:67/udp
        #- 68:68/tcp
        #- 68:68/udp
        # HTTPS/DNS-over-HTTPS
        #- 443:443/tcp
        # DNS-over-TLS
        - 853:853/tcp
        # DNS-over-QUIC
        #- 784:784/udp
        # DNSCrypt
        #- 5443:5443/tcp
        #- 5443:5443/udp
        # WebUI
        - 80:80/tcp
        - 443:443/tcp
        #- 443:443/udp
        # WebUI Setup
        - 3000:3000/tcp
    restart: unless-stopped
```

I can access the web interface via 192.168.0.10, but if i set the DNS on my router to 192.168.0.10 or direct to my Mac under Network Settings, no website will be loaded.

Any idea?

**Comment by Lockszmith-GH** [comment]
My guess is there is a race condition on the 80 and 443 ports. by default Adguard will listen on 0.0.0.0 which means 'all IPs' - you want to force it to listen only on the new static IP you've set.

I have adguard running in a similar fashion, I just used host networking instead for the container - it's 'risky' but it's the only service running in that jail right now.

**Reply by BenRoe** [reply]
In the adguardhome.yaml i tried '127.0.0.1' and '192.168.0.10' for dns, but no luck.

**Reply by Lockszmith-GH** [reply]
not the DNS.

try:

```yaml
dns:
  bind_hosts:
    - 192.168.0.10
```

**Reply by BenRoe** [reply]
Sorry i was referring to

```yaml
dns:
  bind_hosts:
```

Still not working.
Also tried a jail without macvlan (host network). This was also not working. Is that an indication that something else is wrong on my network?
Note, i have a running adguard instance on a RPI.

**Reply by Lockszmith-GH** [reply]
I took another look, the bind is for DNS, but there is also the web bind:

```yaml
http:
...
  address: 192.168.0.10:80
...
dns:
  bind_hosts:
    - 192.168.0.10
  port: 53
...
```

Those are the 2 places where I have my IP listed
