### DISCUSSION TITLE
how to change password for user in jlmkr shell jail?

### DISCUSSION THREAD

**Discussion by mooglestiltzkin** [Jip-Hop/jailmaker#138] [Q&A] [answered]
Ok,

go i login to my jail shell.

then from there i can create a user
`useradd docker`

i can give that user root powers
`usermod -aG sudo docker`

Switch to user
`su -l docker`

> Put a password on Root
> While logged in as root run `passwd`

user creation/management is covered here
https://github.com/Jip-Hop/jailmaker/blob/main/docs/basicconfig.md

https://github.com/Jip-Hop/jailmaker/blob/main/README.md

I tried doing this but it didn't manage to change password.

so i couldn't leave it like that, and so had to remove the user i created
`deluser docker`

Any ideas?

Also any specific recommendations. I just thought if i create a docker user, i can use that for login into the docker shell using those credentials, rather than my truenas root user credentials.

does it make sense doing that? more help and tips on this would be great.

I do understand the basic concepts like, try not to run root for docker containers. A good example is linux server docker containers set a non root user for better security.

Though i am not sure how to apply that concept for jailmaker docker.

**Comment by Jip-Hop** [comment]
I never did anything from this page:
https://github.com/Jip-Hop/jailmaker/blob/main/docs/basicconfig.md
I personally just login to TrueNAS via SSH and operate from there, including logging in to the jail shell.
Just creating a user in a jail like that won't do much, unless you also install and SSH server inside (each) jail and set it up so you can connect to this jail using the user you created. But you'll likely want to connect with SSH keys instead of the user password.
For now I'd recommend not to follow the steps in basicconfig.md and keep it simple.

**Reply by mooglestiltzkin** [reply]
ah ty. so when i deploy docker i just change user uid and gid to 0:0 then? for now i guess hm

**Reply by Jip-Hop** [reply]
I have no idea what you mean. Just enter the jail with jlmkr shell dockerjail and run your docker commands from there. Don't change anything, it should just work already if you're using the docker config template.

**Reply by mooglestiltzkin** [reply]
example

```
---
services:
  librespeed:
    image: lscr.io/linuxserver/librespeed:latest
    container_name: librespeed
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=PASSWORD
      - CUSTOM_RESULTS=false #optional
      - DB_TYPE=sqlite #optional
      - DB_NAME=DB_NAME #optional
      - DB_HOSTNAME=DB_HOSTNAME #optional
      - DB_USERNAME=DB_USERNAME #optional
      - DB_PASSWORD=DB_PASSWORD #optional
      - DB_PORT=DB_PORT #optional
      - IPINFO_APIKEY=ACCESS_TOKEN #optional
    volumes:
      - /path/to/librespeed/config:/config
    ports:
      - 80:80
    restart: unless-stopped
```

https://docs.linuxserver.io/images/docker-librespeed/#usage

set this to 0:0 ? because is root. if not how to create the non root to use for the docker compose to deploy dockers inside jailmaker docker jail?

      - PUID=1000
      - PGID=1000
