### DISCUSSION TITLE
Running Telegraf in a jail and collecting host metrics - stuck with Telegraf simply "Loading Config"

### DISCUSSION THREAD

**Discussion by b-neufeld** [Jip-Hop/jailmaker#169] [Q&A] [answered]
Here's a head-scratcher. 

I'm allllmost done rebuilding my TrueNAS-hosted Ubuntu/Docker VM with jails. Everything is working, even finnicky Frigate.... except for seemingly-simple Telegraf! 

What I want to do seems fairly simple: Use Telegraf in a Docker container with a mount or two to read host metrics (see [here](https://hub.docker.com/_/telegraf) under "Monitoring the Docker Engine Host") and pump them back to my influxdb. 

Please bear with me... this might seem like a Telegraf issue but I had it working on the Ubuntu VM and the TrueNAS SCALE host in tandem before this... so I think it's something to do with Jailmaker and/or mount configuration. 

Here's the first part of my jail config:

```
startup=1
gpu_passthrough_intel=0
gpu_passthrough_nvidia=0
# Turning off seccomp filtering improves performance at the expense of security
seccomp=1

# Use macvlan networking to provide an isolated network namespace,
# so docker can manage firewall rules
# Alternatively use --network-macvlan=eno1 instead of --network-bridge
# Ensure to change eno1/br1 to the interface name you want to use
# You may want to add additional options here, e.g. bind mounts
systemd_nspawn_user_args=--network-bridge=br0
        --resolv-conf=bind-host
        --system-call-filter='add_key keyctl bpf'
        --bind-ro='/:/hostfs'                      # Pass through a read-only copy of the host system
        --bind='/mnt/vesta/apps/telegraf/ceres:/hostconfig'        # where Telegraf logs go 
        --bind='/mnt/vesta/apps/docker/data-telegraf:/app/data'     # for Dockge
        --bind='/mnt/vesta/apps/docker/stacks-telegraf:/opt/stacks'     # for Dockge
...
```
The one thing I wonder about is binding '/' inside the jail. 

Docker compose for Telegraf: 

```
version: "3.8"
services:
  telegraf:
    image: telegraf:latest 
    container_name: telegraf_ceres
    #user: root:root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /hostconfig/telegraf.conf.condensed:/etc/telegraf/telegraf.conf    # mount the config file - this works.
      - /hostconfig:/hostconfig         # passing this through from the jail config for log file storage
      - /hostfs:/hostfs                 # passing through from jail config for 
    environment:
      - HOST_ETC=/hostfs/etc
      - HOST_PROC=/hostfs/proc
      - HOST_SYS=/hostfs/sys
      - HOST_VAR=/hostfs/var
      - HOST_RUN=/hostfs/run
      - HOST_MOUNT_PREFIX=/hostfs
    ports:
      - 8125:8125
    restart: unless-stopped
networks: {}
```

Here's a stripped-down Telegraf config I've been testing with (trying to eliminate something dumb like a typo as a source of error):

```
[global_tags]

[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = "0s"
  debug = true
  quiet = false
  logtarget = "file"
  logfile = "/hostconfig/telegraf.log"
  logfile_rotation_interval = "24h"
  logfile_rotation_max_size = "2MB"
  logfile_rotation_max_archives = 10
  hostname = "ceres"
  omit_hostname = false

[[outputs.influxdb_v2]]
  urls = ["http://myhost:8086"]
  token = "mytoken~~~~~~~~~~~~~~~~~
  organization = "myorg"
  bucket = "mybucket"

[[inputs.mem]]
```

No mater what I do, I see messages like `2024-05-11T04:41:29Z I! Loading config: /etc/telegraf/telegraf.conf` in the container logs and nothing after that, despite enabling debug mode and disabling quiet mode on Telegraf. 

It seems like it's stuck loading the config, but I've ruled out file access issues (Telegraf can see the right config file). I thought Telegraf might not have permissions to write to the logfile, but I've tried changing the config to send errors to `stderr`. 

Any ideas? Thanks!
