### DISCUSSION TITLE
Connect TrueNas App (Prowlarr) to jail docker container (qbittorrent) help

### DISCUSSION THREAD

**Discussion by Matt-Of-Doom** [Jip-Hop/jailmaker#236] [Q&A]
I accidently deleted my qbittorrent instance of the truecharts version and found the recent news of the deprication. In light of this I found several sources pointing me to jlmkr and using dockge to create a qbit container which I eventually did succesfully (shout out to the Capt Stux videos)

The reason I couldn't use the truenas native app is the ability to VPN just qbit like I had in my previous setup, but sounds like it's a potential feature in Q4.

Now my issue is connecting the apps together. Following the video by Capt Stux I made a bridge connection and updated the necessary config in the hopes that my containers would be able to reach out to my local network, but none of my *arr programs can connect with qbit at all.

I've done a lot of digging and found [this post](https://github.com/Jip-Hop/jailmaker/discussions/202) discussing the matter about adding the vb-docker created interface to the bridge and that worked for them. Still doesn't work in my situation though.

My jail can ping my truenas box and vice versa, but I think the issue is when it comes to the container itself having a problem connecting back. Any help would be appreciated as now it's more of wonder of "why doesn't this work" vs just through everything into dockge and just re-setting that up and letting it ride.

compose.yaml

```
version: "3.8"
services:
  gluetun:
    image: qmcgaw/gluetun:latest
    network_mode: bridge
    cap_add:
      - NET_ADMIN
    environment:
      - VPN_SERVICE_PROVIDER=expressvpn
      - VPN_TYPE=openvpn
      - OPENVPN_USER=
      - OPENVPN_PASSWORD=
      - SERVER_COUNTRIES=USA
      - SERVER_CITIES=CHICAGO
      - TZ=USA/Chicago
      - HTTPPROXY=on
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
      - 7878:7878 # radarr
      - 8888:8888/tcp # HTTP proxy
    restart: always
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=USA/Chicago
      - WEBUI_PORT=8080
      - INCOMING_PORT_ENV=8999
      - LAN_NETWORK=192.168.1.0/24
    volumes:
      - /docker/appdata/qbittorrent:/config
      - /data/torrents:/Media
    depends_on:
      gluetun:
        condition: service_healthy
  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1026
      - PGID=101
      - TZ=USA/Chicago
    volumes:
      - /docker/radarr3/config:/config
    restart: unless-stopped
    network_mode: service:gluetun
    depends_on:
      - qbittorrent
networks:
  dockge_default:
    external: true
and my docker ip's

```
docker network devices
```
root@docker:~# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host noprefixroute 
       valid_lft forever preferred_lft forever
2: host0@if12: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 56:eb:9e:03:30:99 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 192.168.1.41/24 brd 192.168.1.255 scope global host0
       valid_lft forever preferred_lft forever
4: br-43616dfd308d: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:cf:2e:f2:ce brd ff:ff:ff:ff:ff:ff
    inet 172.18.0.1/16 brd 172.18.255.255 scope global br-43616dfd308d
       valid_lft forever preferred_lft forever
    inet6 fe80::42:cfff:fe2e:f2ce/64 scope link 
       valid_lft forever preferred_lft forever
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:33:a9:9d:53 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:33ff:fea9:9d53/64 scope link 
       valid_lft forever preferred_lft forever
9: veth263144d@if8: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master br-43616dfd308d state UP group default 
    link/ether 32:b1:43:e4:94:66 brd ff:ff:ff:ff:ff:ff link-netnsid 1
    inet6 fe80::30b1:43ff:fee4:9466/64 scope link 
       valid_lft forever preferred_lft forever
46: veth72bcc26@if45: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master docker0 state UP group default 
    link/ether 2a:21:68:7f:1d:b4 brd ff:ff:ff:ff:ff:ff link-netnsid 3
    inet6 fe80::2821:68ff:fe7f:1db4/64 scope link 
       valid_lft forever preferred_lft forever
root@docker:~#
```
bridge setup
![image](https://github.com/user-attachments/assets/4cc9c221-115d-4ba7-ac20-dffd922fc2c4)
