### ISSUE TITLE
Truenas middleware no longer responds at all with a large qbittorrent instance

### ISSUE THREAD

**Issue by SeiyaGame** [Jip-Hop/jailmaker#151]
I carried out several tests over 2 weeks and realized that when I launch my docker qbittorrent instance via my jail, after a while my Truenas middleware no longer responds.

<details>
<summary>Here's my docker-compose.yaml file</summary>

```yaml
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    ports:
      - 10095:10095 # qBittorrent Web UI
    environment:
      - PUID=568
      - PGID=568
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - VPN_ENDPOINT_IP=IP_VPN_PROVIDER_KEY_PUT_HERE
      - VPN_ENDPOINT_PORT=1443
      - FIREWALL_VPN_INPUT_PORTS=50025
      - WIREGUARD_PUBLIC_KEY=PUBLIC_KEY_PUT_HERE
      - WIREGUARD_PRIVATE_KEY=PRIVATE_KEY_PUT_HERE
      - WIREGUARD_ADDRESSES=10.13.128.113/24
      - DNS_KEEP_NAMESERVER=on
      - TZ=Europe/Paris
      - HTTPPROXY=off
      - SHADOWSOCKS=off
      - FIREWALL_OUTBOUND_SUBNETS=192.168.5.0/24 # Your Subnet
      - WIREGUARD_MTU=1390 # Default is 1500 but some provider change this for better performance
    volumes:
      - ./gluetun:/gluetun
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    deploy:
      resources:
        limits:
          cpus: "16.0"
          memory: 16G
    environment:
      - PUID=568
      - PGID=568
      - TZ=Europe/Paris
      - WEBUI_PORT=10095
      - TORRENTING_PORT=50025
    volumes:
      - ./config:/config
      - /mnt/shared/downloads/torrents:/shared/downloads/torrents
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s https://www.google.fr || exit 1
      interval: 1m
      timeout: 10s
      retries: 1
    restart: unless-stopped
```

</details>

For my jail, I used the template [here](https://github.com/Jip-Hop/jailmaker/blob/main/templates/docker/config), and only passthrough the nvidia gpu.

Today, my qbittorrent instance has over 8500 torrents, it works fine with kubernetes but as I said above, when I start my qbit instance in the jail, my truenas become unresponsive over time, the whole system lags and all this doesn't happen instantly!

I turn off my qbit instance and the web interface (middleware) and the system of my truenas work perfectly (sometimes I need to restart the middleware anyway).

Being a bit desperate, I'm turning to you for an idea of why this is happening...

I can do tests if you wish and don't hesitate if you want more information!
