### ISSUE TITLE
k3s example?

### ISSUE THREAD

**Issue by javydekoning** [Jip-Hop/jailmaker#191]
**Describe the solution you'd like**
Your example configs are super helpful, with Ix moving away from k3s in Electric Eel it would be super helpful to get a config example up for k3s.

I'm guessing it wil be similar to the Docker one, just replacing the install command with:

```sh
    curl -sfL https://get.k3s.io | \
    INSTALL_K3S_CHANNEL=latest sh -s - server --cluster-init
```

You already have `net.ipv4.ip_forward=1` in the Docker example, but for my k3s host I've ran into 2 other limits (see below Ansible example)

```yaml
- name: 02-PREP_set_net.ipv4.ip_forward=1
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes
    sysctl_set: true

- name: 02-PREP_set_fs.inotify.max_user_watches=655360
  when: container_check_result.stdout_lines[0] == "Not running inside a container"
  sysctl:
    name: fs.inotify.max_user_watches
    value: "655360"
    state: present
    reload: yes
    sysctl_set: true

- name: 02-PREP_set_fs.inotify.max_user_instances=1280
  when: container_check_result.stdout_lines[0] == "Not running inside a container"
  sysctl:
    name: fs.inotify.max_user_instances
    value: "1280"
    state: present
    reload: yes
    sysctl_set: true
```

I don't have an environment today for which I can contribute this, but will have a new host coming in a week or 2 and can contribute to it then.
